version: '3.8'

services:
  mcp-server:
    image: lightrag/mcp-server:latest
    ports:
      - "8001:8001"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mcp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - neo4j
      - postgres

  neo4j:
    image: neo4j:5.13.0
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  postgres:
    image: postgres:15.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mcp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  neo4j_data:
  neo4j_logs:
  postgres_data: 